version: 0.0
os: linux
files:
  - source: target/petclinic.war
    destination: /tomcat8/webapps/
hooks:
  ApplicationStop:
    - location: scripts/shutdown_tomcat.sh
      timeout: 100
  ApplicationStart:
    - location: scripts/startup.sh
      timeout: 180
  ValidateService:
    - location: scripts/basic_health_check.sh
